# Generated by Django 2.1.2 on 2018-10-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=64)),
                ('middle_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('membership_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('description', models.TextField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pan', models.CharField(max_length=200)),
                ('aadhar', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('permanent_address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=200)),
                ('name_of_individual', models.CharField(max_length=200)),
                ('va_type', models.CharField(choices=[('Indivisual', 'indivisual'), ('Professional', 'Professional'), ('CS', 'CS'), ('LAWYER', 'Lawyer')], max_length=8)),
            ],
        ),
    ]
