# Generated by Django 2.1.2 on 2018-10-13 09:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerprofile',
            name='membership_number',
        ),
        migrations.AddField(
            model_name='registerprofile',
            name='mobile_no_of_friend',
            field=models.CharField(default=datetime.datetime(2018, 10, 13, 9, 36, 29, 782289, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='mobile_no',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='va_type',
            field=models.CharField(choices=[('Indivisual', 'indivisual'), ('Professional', 'Professional')], max_length=8),
        ),
    ]
