# Generated by Django 2.1.2 on 2018-10-13 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181013_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerprofile',
            old_name='mobile_no_of_friend',
            new_name='mobile_no_of_relative',
        ),
        migrations.RenameField(
            model_name='registerprofile',
            old_name='name_of_individual',
            new_name='name_of_relative',
        ),
        migrations.AddField(
            model_name='registerprofile',
            name='blood_type',
            field=models.CharField(default=datetime.datetime(2018, 10, 13, 11, 16, 41, 79242, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='va_type',
            field=models.CharField(choices=[('Indivisual', 'indivisual'), ('Professional', 'Professional')], max_length=20),
        ),
    ]
