# Generated by Django 2.1.2 on 2018-10-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181013_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerprofile',
            old_name='blood_type',
            new_name='blood_group',
        ),
    ]
