# Generated by Django 2.1.2 on 2018-10-13 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181013_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerprofile',
            name='last_name',
            field=models.CharField(db_index=True, default=datetime.datetime(2018, 10, 13, 12, 58, 18, 683440, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='middle_name',
            field=models.CharField(db_index=True, default=datetime.datetime(2018, 10, 13, 12, 58, 28, 275949, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='mobile_no',
            field=models.CharField(db_index=True, default=datetime.datetime(2018, 10, 13, 12, 58, 40, 67856, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
    ]
