# Generated by Django 2.1.2 on 2018-10-13 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181013_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerprofile',
            name='emergency_contact',
            field=models.CharField(default=datetime.datetime(2018, 10, 13, 13, 39, 41, 581876, tzinfo=utc), max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='aadhar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='mobile_no_of_relative',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='pan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
